---
# Common tasks applicable to both Oracle and OpenJDK

# this directory will contain the Java downloads
- name: Install Java download directory (local)
  tags: java
  local_action: file
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ ansible_data_path }}


# Test whether we need to download Java.
- name: Install Oracle Java redis package sha256sum (local)
  tags: java
  local_action: template
    src=sha256sum.j2
    dest={{ ansible_data_path }}/java.sha256sum


# Ansile requirement if SELinux is enabled
- include: selinux.yml
  tags: java
