---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform,
- name: Assert platform is supported
  tags: java
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
      - ansible_architecture in ['x86_64']

- name: Assert java_oracle_distribution value
  tags: java
  assert:
    that:
      - java_oracle_distribution in ('jre', 'jdk')

# Overide variables based on known/supported Java versions
- name: Load version vars
  tags: java
  with_first_found:
    - ../vars/versions/{{ java_oracle_version }}.yml
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: Assert version vars
  tags: java
  assert:
    that:
      - java_oracle_redis_{{ java_oracle_distribution }}_sha256sum not in (None, "")
      - java_oracle_redis_jce_sha256sum not in (None, "")

- name: Include OS specific vars
  tags: java
  include_vars: "{{ ansible_os_family }}.yml"


# Manage local download of Oracle Java redistributable
- include: download.yml
  tags:
    - java
    - download


- name: Install required packages
  tags: java
  become: yes
  with_items: java_package_list
  action: "{{ ansible_pkg_mgr }} state={{ util_package_state }} name={{ item }}"


# Install Oracle Java JDK

# Directory for unarchiving the configured version of Java.
- name: Install Java base directory
  tags: java
  become: yes
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ java_install_dir }}/oracle

# Install the Oracle redistributable package to the node
- name: Copy Java redistributable packages
  tags: java
  become: yes
  with_items: ["{{ java_oracle_redis_filename }}", "{{ java_oracle_redis_jce_filename }}"]
  copy:
    src={{ util_persistent_data_path_local }}/{{ item }}
    dest={{ util_persistent_data_path_remote }}/{{ item }}
    owner=0
    group=0
    mode=0644

- name: Install Java
  tags: java
  become: yes
  unarchive:
    src={{ util_persistent_data_path_remote }}/{{ java_oracle_redis_filename }}
    dest={{ java_install_dir }}/oracle/
    copy=false
    creates={{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}

- name: Unarchive Java JCE package
  tags: java
  unarchive:
    src={{ util_persistent_data_path_remote }}/{{ java_oracle_redis_jce_filename }}
    dest=/tmp/
    copy=false
    creates=/tmp/{{ java_oracle_redis_jce_archive_dirname }}


- name: Install Java JCE policies to JRE
  tags: java
  become: yes
  when: java_oracle_distribution == 'jre'
  changed_when: false
  with_items:
    - local_policy.jar
    - US_export_policy.jar
  command: install
      --owner root
      --group root
      --mode 0644
      /tmp/{{ java_oracle_redis_jce_archive_dirname }}/{{ item }}
      {{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}/lib/security/{{ item }}

- name: Install Java JCE policies to JDK
  tags: java
  become: yes
  when: java_oracle_distribution == 'jdk'
  changed_when: false
  with_items:
    - local_policy.jar
    - US_export_policy.jar
  command: install
      --owner root
      --group root
      --mode 0644
      /tmp/{{ java_oracle_redis_jce_archive_dirname }}/{{ item }}
      {{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}/jre/lib/security/{{ item }}


# Archives may be packaged with some useless uid and gid
- name: Fixup filesystem permissions
  tags: java
  become: yes
  file:
    state=directory
    owner=0
    group=0
    recurse=true
    dest={{ java_install_dir }}


# Setup a custom fact to allow roles depending on Java to configure
#   JAVA_HOME variable
- name: Set JAVA_HOME ansible fact
  tags: java
  set_fact:
    java_home={{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}

- name: Install Ansible facts.d directory
  tags: java
  become: yes
  file:
    state=directory
    dest=/etc/ansible/facts.d
    owner=0
    group=0
    mode=0755

- name: Install java facts
  tags: java
  become: yes
  template:
    src=facts.j2
    dest=/etc/ansible/facts.d/java.fact
    owner=0
    group=0
    mode=0644

- name: Re-read local facts
  tags: java
  setup:
    filter=ansible_local


# Configure Java installation as system wide default Java
- name: Install Java default implementation
  tags: java
  become: yes
  template:
    src=java.sh.j2
    dest={{ java_install_dir }}/java.sh
    owner=0
    group=0
    mode=0755

- name: Activate Java system environment configuration
  tags: java
  become: yes
  file:
    state=link
    src={{ java_install_dir }}/java.sh
    dest=/etc/profile.d/java.sh
