---
- name: Assert platform is supported
  tags:
    - java
    - java_download
  assert:
    that:
      - ansible_os_family in java_supported_platform
      - ansible_architecture in ['x86_64']

- name: Assert java_oracle_distribution value
  tags:
    - java
    - java_download
  assert:
    that:
      - java_oracle_distribution in ('jdk', 'jre', 'srv')

- name: Configure initial --check_mode fact
  tags:
    - java
    - java_download
  when:
    - ansible_check_mode
    - not (ansible_local|default({})).java is defined
  set_fact:
    java_fact_initial_check_mode: true


- name: Include version specific configuration
  tags:
    - java
    - java_download
  include: "{{ java_path_to_lib_role }}/silpion.lib/tasks/version-specific-vars.yml"
  vars:
    version: "{{ java_oracle_version }}"

- name: Assert version specific configuration
  tags:
    - java
    - java_download
  assert:
    that:
      - java_oracle_redis_{{ java_oracle_distribution }}_sha256sum not in (None, "")
      - java_oracle_redis_jce_sha256sum not in (None, "")


- name: Include OS specific configuration
  tags: java
  include: "{{ java_path_to_lib_role }}/silpion.lib/tasks/os-specific-vars.yml"


- name: Include assets persistency tasks
  tags: java
  include: "{{ java_path_to_lib_role }}/silpion.lib/tasks/datapersistency.yml"


# Manage local download of Oracle Java redistributable
- name: Manage download of Java redistributables
  include: download.yml
  when: not ansible_check_mode
  tags:
    - java
    - download
    - java_download


- name: Install required packages
  tags: java
  become: true
  with_items: "{{ java_package_list }}"
  package:
    state: "{{ util_package_state|default('present') }}"
    name: "{{ item }}"


# Install Oracle Java JDK

# Directory for unarchiving the configured version of Java.
- name: Install Java base directory
  tags: java
  become: true
  file:
    state: directory
    owner: 0
    group: 0
    mode: 0755
    dest: "{{ java_install_dir }}/oracle"

# Install the Oracle redistributable package to the node
- name: Copy Java redistributable packages
  tags: java
  when: not ansible_check_mode
  with_items:
    - "{{ java_oracle_redis_filename }}"
    - "{{ java_oracle_redis_jce_filename }}"
  include: "{{ java_path_to_lib_role }}/silpion.lib/tasks/copy.yml"
  vars:
    filename: "{{ item }}"

- name: Install Java
  tags: java
  become: true
  when: not ansible_check_mode
  unarchive:
    src: "{{ lib_persistent_data_path_remote }}/{{ java_oracle_redis_filename }}"
    dest: "{{ java_install_dir }}/oracle/"
    copy: false
    creates: "{{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}"

- name: Unarchive Java JCE package
  tags: java
  when: not ansible_check_mode
  unarchive:
    src: "{{ lib_persistent_data_path_remote }}/{{ java_oracle_redis_jce_filename }}"
    dest: /tmp/
    copy: false
    creates: /tmp/{{ java_oracle_redis_jce_archive_dirname }}


- name: Install Java JCE policies
  tags: java
  become: true
  when: not ansible_check_mode
  changed_when: false
  with_items:
    - local_policy.jar
    - US_export_policy.jar
  command: install
      --owner root
      --group root
      --mode 0644
      /tmp/{{ java_oracle_redis_jce_archive_dirname }}/{{ item }}
      {{ java_oracle_jce_install_dir }}/{{ item }}



# Archives may be packaged with some useless uid and gid
- name: Fixup filesystem permissions
  tags: java
  become: true
  file:
    state: directory
    owner: 0
    group: 0
    recurse: true
    dest: "{{ java_install_dir }}"


- name: Include local facts tasks
  tags: java
  include: "{{ java_path_to_lib_role }}/silpion.lib/tasks/localfacts.yml"
  vars:
    namespace: java


# Configure Java installation as system wide default Java
- name: Install Java default implementation
  tags: java
  become: true
  template:
    src: java.sh.j2
    dest: "{{ java_install_dir }}/java.sh"
    owner: 0
    group: 0
    mode: 0755

- name: Activate Java system environment configuration
  tags: java
  become: true
  when: not ansible_check_mode
  file:
    state: link
    src: "{{ java_install_dir }}/java.sh"
    dest: /etc/profile.d/java.sh
